name: Update Readme

on:
  push:
    branches: main

  schedule:
    - cron: "0 */12 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install
        run: npm ci
      - name: Update gist
        run: node ./index.js
        env:
          GH_TOKEN: ${{ secrets.GiTHUB_TOKEN }}
          WK_KEY: ${{ secrets.WK_KEY }}
